### ISSUE TITLE
一些問題

### ISSUE THREAD

**Issue by kenneth-lin-2003** [NTU-SP/SP2023_HW1_release#2]
同個server可能會有一個client post指令發出，有可能此時還沒有輸入內容，同時有另一個client發出pull的指令。但是post那裡會卡住。因為沒有完成輸入內容。一直卡在post那裡

Board的裡面一開始就會有RECORD NUM 乘以 record大小的bytes 嗎

讀BulletinBoard和<user_input>可以直接使用blocking IO是指我可以一次讀完整個Board嗎。不需要分多次一次只讀一點，就去執行其他client的指令

麻煩助教們回答問題。謝謝

**Comment by cpy0126** [comment]
1.I/O multiplexing 可以解決
2.可以參考 sampletestcases
3.是
